// app/[locale]/layout.tsx

import '../globals.css'
import type { Metadata } from 'next'
import '@mantine/core/styles.css';
import { ReactNode } from 'react';
import { MantineProvider, ColorSchemeScript } from '@mantine/core';
import { notFound } from 'next/navigation'
import { NextIntlClientProvider } from 'next-intl'
import { theme } from '@/theme';
import { Header } from '@/components/Header/Header';
import { Footer } from '@/components/Footer/Footer';

import footerTranslations from '@/dictionaries/footer/en.json';
import metaDataTranslations from '@/dictionaries/metaData/en.json';

type Props = {
  children: ReactNode
  params: { locale: string }
}

export const metadata: Metadata = metaDataTranslations;

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

//function to get the translations
async function getMessages(locale: string) {
  try {
    return (await import(`../../messages/${locale}.json`)).default
  } catch (error) {
    notFound()
  }
}

//function to generate the routes for all the locales
export async function generateStaticParams() {
  return ['lt', 'en',].map((locale) => ({ locale }))
}



export default async function RootLayout({
  children,
  params: { locale },
}: Props) {
  const messages = await getMessages(locale)

  return (
    <html lang={locale}>
      <head>
        <ColorSchemeScript />
        <link rel="shortcut icon" href="/favicon.svg" />
        <meta
          name="viewport"
          content="minimum-scale=1, initial-scale=1, width=device-width, user-scalable=no"
        />
      </head>
      <body>
        <MantineProvider theme={theme}>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <Header/>
          {children}
          <Footer text={footerTranslations} />
        </NextIntlClientProvider>
        </MantineProvider>
      </body>
    </html>
  );
}
